version: '3.8'

services: 
  node_backend:
    container_name: node_app_container
    image: node_crud_app:0.0.2
    restart: always
    build: 
      context: .
    ports:
      - "5000:5000"
    environment: 
      - EXTERNAL_PORT=5000
      - PGDATABASE=node_db
      - PGUSER=docker
      - PGPASSWORD=Welcome@123
      - PGHOST=postgres_db
    depends_on: 
      - postgres_db

  postgres_db:
    container_name: postgres_database
    image: "postgres:12"
    restart: always
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=Welcome@123
      - POSTGRES_DB=node_db
    volumes:
      - node_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"

volumes:
  node_data: {}

  
    